language: csharp
solution: Travis.sln
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0
script:
    - dotnet restore
//    - dotnet test 
    - dotnet vstest ((ls -Recurse *Tests.dll | % FullName) -Match "\\bin\\Release\\")
    - dotnet publish -c release

