language: csharp
solution: Travis.sln
install:
    - nuget restore Travis.sln
    - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
script:
    - xbuild /p:Configuration=Release Travis.sln
    - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./TravisTests/bin/Release/TravisTests.dll

